server:
  port: 8083

spring:
  application:
    name: hotels-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

